services:
  - type: worker
    name: content-worker
    env: node
    plan: starter
    buildCommand: npm ci
    startCommand: npm run start:worker
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: VERCEL_BASE
        sync: false
      - key: GEMINI_API_BASE
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "nanobanana"
      - key: HIGGSFIELD_API_KEY
        sync: false
      - key: HIGGSFIELD_API_SECRET
        sync: false
      - key: HIGGSFIELD_PLATFORM_API_BASE
        value: "https://platform.higgsfield.ai/v1"
      - key: HIGGSFIELD_MODEL
        value: "seedance pro"
      - key: HIGGSFIELD_MOTION_ID
        value: "cb27169d-aba4-43d9-8667-3292966b2de5"
      - key: HIGGSFIELD_ENHANCE_PROMPT
        value: "true"

